Repository Lidiajim/montaito-hub, pull requests merged in 2024-11, with the labels that each got.

#14 Feature/#5 remember my password
  app/modules/auth/forms.py
  app/modules/auth/routes.py
  app/modules/auth/services.py
  app/modules/auth/templates/auth/login_form.html
  app/modules/auth/templates/auth/remember_password_form.html
  app/modules/auth/templates/auth/reset_password_form.html
  app/modules/auth/tests/test_seleniu_rem.py
  app/modules/profile/forms.py
  app/modules/profile/routes.py
  app/modules/profile/templates/profile/reset_password_form.html
  app/modules/profile/templates/profile/summary.html
  app/modules/profile/tests/test_selenium.py
Labels: feature, M2, high priority, low

#15 Feature/#4 view user profile
  app/modules/dataset/models.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/view_dataset.html
  app/modules/dataset/tests/test_viewporfilewithlogin.py
  app/modules/dataset/tests/test_viewporfilewithoutlogin.py
  app/modules/profile/routes.py
  app/modules/profile/templates/profile/profile.html
Labels: feature, test, M2, high priority, low

#16 Feature/#7 rate datasets models
  app/modules/dataset/models.py
  app/modules/dataset/routes.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/view_dataset.html
  app/modules/dataset/tests/test_rate_dataset.py
  app/modules/featuremodel/models.py
  app/modules/featuremodel/routes.py
  app/modules/featuremodel/services.py
  app/modules/featuremodel/tests/test_rate_featuremodel.py
  app/static/css/model.css
  app/static/css/stars.css
  migrations/versions/5cff3147d484_.py
  migrations/versions/a710b3626381_.py
Labels: feature, test, M2, high priority, medium

#17 Feature/#10 fakenodo
  app/modules/fakenodo/__init__.py
  app/modules/fakenodo/assets/scripts.js
  app/modules/fakenodo/depositions.json
  app/modules/fakenodo/forms.py
  app/modules/fakenodo/models.py
  app/modules/fakenodo/repositories.py
  app/modules/fakenodo/routes.py
  app/modules/fakenodo/seeders.py
  app/modules/fakenodo/services.py
  app/modules/fakenodo/templates/index.html
  app/modules/fakenodo/tests/__init__.py
  app/modules/fakenodo/tests/locusfile.py
  app/modules/fakenodo/tests/test_selenium.py
  app/modules/fakenodo/tests/test_unit.py
  migrations/versions/56a2c1c30c95_create_notepad_model.py
  migrations/versions/c4344d7e3b1f_.py
Labels: feature, test, M2, high priority, high

#20 fix: Add new general migration
  migrations/versions/5a52d6aa58aa_.py
  migrations/versions/5cff3147d484_.py
  migrations/versions/6986d809ce3f_.py
  migrations/versions/a710b3626381_.py
Labels: bug, high priority

#30 Bugfix/#22 bug codacy
  .github/workflows/codacy.yml
Labels: bug, fix, 2, M3, config

#29 Feature/#6 dashboard
  app/modules/dashboard/__init__.py
  app/modules/dashboard/assets/scripts.js
  app/modules/dashboard/repositories.py
  app/modules/dashboard/routes.py
  app/modules/dashboard/services.py
  app/modules/dashboard/templates/dashboard/index.html
  app/modules/dashboard/templates/dashboard/profile_dashboard.html
  app/modules/dashboard/tests/__init__.py
  app/modules/dashboard/tests/locustfile.py
  app/modules/dashboard/tests/test_selenium.py
  app/modules/dashboard/tests/test_unit.py
  app/modules/dataset/repositories.py
  app/modules/featuremodel/repositories.py
  app/static/js/index_dashboard.js
  app/static/js/rating_stars.js
  app/templates/base_template.html
Labels: feature, medium, M3

#32 upgrade: Add datasets ranking
  app/modules/dataset/routes.py
  app/modules/dataset/services.py
  app/modules/public/templates/public/index.html
  app/modules/ranking/__init__.py
  app/modules/ranking/assets/scripts.js
  app/modules/ranking/routes.py
  app/modules/ranking/templates/ranking/index.html
  app/templates/base_template.html
Labels: 1, M3, upgrade
